parameters:
    open_orchestra_display.display_block_manager.class: OpenOrchestra\DisplayBundle\DisplayBlock\DisplayBlockManager
    open_orchestra_display.display.contact.class: OpenOrchestra\DisplayBundle\DisplayBlock\Strategies\ContactStrategy
    open_orchestra_display.display.footer.class: OpenOrchestra\DisplayBundle\DisplayBlock\Strategies\FooterStrategy
    open_orchestra_display.display.menu.class: OpenOrchestra\DisplayBundle\DisplayBlock\Strategies\MenuStrategy
    open_orchestra_display.display.sample.class: OpenOrchestra\DisplayBundle\DisplayBlock\Strategies\SampleStrategy
    open_orchestra_display.display.tiny_mce_wysiwyg.class: OpenOrchestra\DisplayBundle\DisplayBlock\Strategies\TinyMCEWysiwygStrategy
    open_orchestra_display.display.configurable_content.class: OpenOrchestra\DisplayBundle\DisplayBlock\Strategies\ConfigurableContentStrategy
    open_orchestra_display.display.sub_menu.class: OpenOrchestra\DisplayBundle\DisplayBlock\Strategies\SubMenuStrategy
    open_orchestra_display.display.content_list.class: OpenOrchestra\DisplayBundle\DisplayBlock\Strategies\ContentListStrategy
    open_orchestra_display.display.content.class: OpenOrchestra\DisplayBundle\DisplayBlock\Strategies\ContentStrategy
    open_orchestra_display.display.language_list.class: OpenOrchestra\DisplayBundle\DisplayBlock\Strategies\LanguageListStrategy
    open_orchestra_display.display.language_list.template: OpenOrchestraDisplayBundle:Block/LanguageList:show.html.twig
    open_orchestra_display.display.gmap.class: OpenOrchestra\DisplayBundle\DisplayBlock\Strategies\GmapStrategy
    open_orchestra_display.display.add_this.class: OpenOrchestra\DisplayBundle\DisplayBlock\Strategies\AddThisStrategy
    open_orchestra_display.display.audience_analysis.class: OpenOrchestra\DisplayBundle\DisplayBlock\Strategies\AudienceAnalysisStrategy
    open_orchestra_display.display.video.class: OpenOrchestra\DisplayBundle\DisplayBlock\Strategies\VideoStrategy

services:
    open_orchestra_display.display_block_manager:
        class: %open_orchestra_display.display_block_manager.class%
        arguments:
            - @templating
            - @open_orchestra_display.manager.cacheable
            - @open_orchestra_base.manager.tag
            - @open_orchestra_display.manager.site
            - @event_dispatcher
    open_orchestra_display.display.contact:
        class: %open_orchestra_display.display.contact.class%
        arguments:
            - @form.factory
            - @request_stack
            - @event_dispatcher
        tags:
            - { name: open_orchestra_display.display_block.strategy }
    open_orchestra_display.display.footer:
        class: %open_orchestra_display.display.footer.class%
        arguments:
            - @open_orchestra_model.repository.node
            - @open_orchestra_base.manager.tag
        tags:
            - { name: open_orchestra_display.display_block.strategy }
    open_orchestra_display.display.menu:
        class: %open_orchestra_display.display.menu.class%
        arguments:
            - @open_orchestra_model.repository.node
            - @open_orchestra_base.manager.tag
        tags:
            - { name: open_orchestra_display.display_block.strategy }
    open_orchestra_display.display.sample:
        class: %open_orchestra_display.display.sample.class%
        tags:
            - { name: open_orchestra_display.display_block.strategy }
    open_orchestra_display.display.tiny_mce_wysiwyg:
        class: %open_orchestra_display.display.tiny_mce_wysiwyg.class%
        arguments:
            - @open_orchestra_bbcode.parser
        tags:
            - { name: open_orchestra_display.display_block.strategy }
    open_orchestra_display.display.configurable_content:
        class: %open_orchestra_display.display.configurable_content.class%
        arguments:
            - @open_orchestra_model.repository.content
            - @open_orchestra_base.manager.tag
            - @open_orchestra_bbcode.parser
        tags:
            - { name: open_orchestra_display.display_block.strategy }
    open_orchestra_display.display.sub_menu:
        class: %open_orchestra_display.display.sub_menu.class%
        arguments:
            - @open_orchestra_model.repository.node
            - @request_stack
            - @open_orchestra_base.manager.tag
        tags:
            - { name: open_orchestra_display.display_block.strategy }
    open_orchestra_display.display.content_list:
        class: %open_orchestra_display.display.content_list.class%
        arguments:
            - @open_orchestra_model.repository.content
            - @open_orchestra_model.repository.node
            - @open_orchestra_base.manager.tag
            - @open_orchestra_bbcode.parser
        tags:
            - { name: open_orchestra_display.display_block.strategy }
    open_orchestra_display.display.content:
        class: %open_orchestra_display.display.content.class%
        arguments:
            - @open_orchestra_model.repository.content
            - @request_stack
            - @open_orchestra_base.manager.tag
            - @open_orchestra_bbcode.parser
        tags:
            - { name: open_orchestra_display.display_block.strategy }
    open_orchestra_display.display.language_list:
        class: %open_orchestra_display.display.language_list.class%
        arguments:
            - @router
            - @open_orchestra_display.manager.site
            - @open_orchestra_model.repository.site
            - @request_stack
            - %open_orchestra_display.display.language_list.template%
        tags:
            - { name: open_orchestra_display.display_block.strategy }
    open_orchestra_display.display.gmap:
        class: %open_orchestra_display.display.gmap.class%
        tags:
            - { name: open_orchestra_display.display_block.strategy }
    open_orchestra_display.display.add_this:
        class: %open_orchestra_display.display.add_this.class%
        tags:
            - { name: open_orchestra_display.display_block.strategy }
    open_orchestra_display.display.audience_analysis:
        class: %open_orchestra_display.display.audience_analysis.class%
        arguments:
            - @request_stack
        tags:
            - { name: open_orchestra_display.display_block.strategy }
    open_orchestra_display.display.video:
        class: %open_orchestra_display.display.video.class%
        tags:
            - { name: open_orchestra_display.display_block.strategy }
