parameters:
    open_orchestra_display.manager.tree.class: OpenOrchestra\DisplayBundle\Manager\TreeManager
    open_orchestra_display.manager.site.class: OpenOrchestra\DisplayBundle\Manager\SiteManager
    open_orchestra_display.manager.cacheable.class: OpenOrchestra\DisplayBundle\Manager\CacheableManager

services:
    open_orchestra_display.manager.tree:
        class: %open_orchestra_display.manager.tree.class%
    open_orchestra_display.manager.site:
        class: %open_orchestra_display.manager.site.class%
        arguments:
            - @request_stack
    open_orchestra_display.manager.cacheable:
        class: %open_orchestra_display.manager.cacheable.class%
        arguments:
            - @fos_http_cache.handler.tag_handler
