parameters:
    open_orchestra_display.bbcode.code_definitions.class: OpenOrchestra\DisplayBundle\BBcode\DisplayBundleBBcodeCollection
    open_orchestra_display.bbcode.internal_link_definitions.class: OpenOrchestra\DisplayBundle\BBcode\InternalLinkDefinition

services:
    open_orchestra_display.bbcode.internal_link_definitions:
        class: '%open_orchestra_display.bbcode.internal_link_definitions.class%'
        arguments:
            - '@router'
            - '@open_orchestra_display.manager.node'
            - '@templating'
    open_orchestra_display.bbcode.code_definitions:
        class: '%open_orchestra_display.bbcode.code_definitions.class%'
        arguments:
            - '@open_orchestra_bbcode.definition.factory'
            - '@open_orchestra_display.bbcode.internal_link_definitions'
        tags:
            - { name: open_orchestra_bbcode.code_definitions }
