parameters:
    open_orchestra_cms.twig.tree.extension.class: OpenOrchestra\DisplayBundle\Twig\TreeHelperExtension
    open_orchestra_cms.twig.navigator.extension.class: OpenOrchestra\DisplayBundle\Twig\NavigatorExtension

services:
    open_orchestra_display.twig.tree.extension:
        class: '%open_orchestra_cms.twig.tree.extension.class%'
        arguments:
            - '@open_orchestra_display.manager.tree'
        tags:
            - { name: twig.extension }
    open_orchestra_display.twig.navigator.extension:
        class: '%open_orchestra_cms.twig.navigator.extension.class%'
        arguments:
            - '@translator'
        tags:
            - { name: twig.extension }
    twig.extension.string_loader:
        class: Twig_Extension_StringLoader
        tags:
            - { name: twig.extension }
