language: php

php:
  - 5.4

cache:
  directories:
    - ~/.composer/cache

sudo: false

install:
  - composer install --no-progress --prefer-dist

script: ./bin/phpunit

addons:
  code_climate:
    repo_token: 9e8441a5e2145a633a1fe2e3159cda6de12bd5b24e262e58a34875715503aba7

after_script:
  - ./bin/test-reporter
