language: php

php:
  - 5.6

cache:
  directories:
    - ~/.composer/cache
    - ~/composer

sudo: false

before_install:
  - if [ -f ~/composer/composer.phar ]; then mv ~/composer/composer.phar ./; else wget https://getcomposer.org/composer.phar; fi
  - mkdir -p ~/composer
  - cp composer.phar ~/composer/composer.phar

install:
  - php -d memory_limit=-1 ./composer.phar install --no-progress --prefer-dist

script: ./bin/phpunit

addons:
  code_climate:
    repo_token: 9e8441a5e2145a633a1fe2e3159cda6de12bd5b24e262e58a34875715503aba7

after_script:
  - ./bin/test-reporter
